name: CI
on:
  push:
    branches: [ test-actions ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LISP: [sbcl, ccl]
        OPENSSL: [openssl-1.1.0j, openssl-1.0.0s]
        BITS: [64]
    env:
      ROSWELL_INSTALL_DIR: ~/.roswell
      LISP: ${{ matrix.LISP }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download roswell install script
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh > install-for-ci.sh

      - name: Cache .roswell
        id: cache-roswell
        uses: actions/cache@v2
        with:
          path: ~/.roswell
          key: roswell-${{ matrix.LISP }}-${{ hashFiles('install-for-ci.sh') }}

      - name: Install Roswell
        run: sh install-for-ci.sh

      - name: Cache OpenSSL libraries
        id: cache-openssl
        uses: actions/cache@v2
        with:
          path: test/run-on-many-lisps-and-openssls/openssl-releases/bin/
          key: openssl-${{ matrix.OPENSSL }}-${{ matrix.BITS }}

      - name: Build OpenSSL libraries
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          test/run-on-many-lisps-and-openssls/openssl-releases/fetch.sh "${{ matrix.OPENSSL }}"
          rm -rf test/run-on-many-lisps-and-openssls/openssl-releases/bin/
          test/run-on-many-lisps-and-openssls/openssl-releases/build.sh "${{ matrix.OPENSSL }}" "${{ matrix.BITS }}" > openssl-build.log


      - name: Run cl+ssl tests
        run: |
          ros -e '(progn
                   (format t "(lisp-implementation-type): ~A~%" (lisp-implementation-type))
                   (format t "(lisp-implementation-version): ~A~%" (lisp-implementation-version))
                   (format t "*features*: ~A~%" *features*)
                   (format t "(asdf:asdf-version): ~A~%" (asdf:asdf-version)))' \
              -e '(ql:quickload :cl+ssl/config :silent t)' \
              -e '(cl+ssl:define-libcrypto-path "test/run-on-many-lisps-and-openssls/openssl-releases/bin/'${{ matrix.OPENSSL }}-${{ matrix.BITS }}bit'/lib/libcrypto.so")' \
              -e '(cl+ssl:define-libssl-path "test/run-on-many-lisps-and-openssls/openssl-releases/bin/'${{ matrix.OPENSSL }}-${{ matrix.BITS }}bit'/lib/libssl.so")' \
              -e '(ql:quickload :cl+ssl.test :silent t)' \
              -e '(let ((results (5am:run :cl+ssl)))
                    (5am:explain! results)
                    (unless (5am:results-status results)
                      (uiop:quit 1)))'
