name: CI
on:
  push:
    branches: [ test-actions ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ROSWELL_INSTALL_DIR: ~/.roswell
    strategy:
      matrix:
        LISP: [sbcl]
        OPENSSL: [openssl-1.1.0j]
        BITS: [64]

    steps:

      - name: Install Roswell
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

      - name: Checkout repo
        uses: actions/checkout@v2

      - run: ls -a ~
      - run: ls -a ~/.roswell
      - run: which ros
