name: CI
on:
  push:
    branches: [ test-actions ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ROSWELL_INSTALL_DIR: $HOME/.roswell
      LISP: ccl

    steps:

      - name: Download Roswell
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh > install-for-ci.sh

      - name: Cache Roswell
        id: cache-roswell
        uses: actions/cache@v2
        with:
          path: ~/.roswell
          key: $${{ runner.os }}-${{ hashFiles('install-for-ci.sh') }}

      - name: Install Rowswell
        run: |
          sh install-for-ci.sh

      - name: Checkout repo
        uses: actions/checkout@v2

      - run: |
          ls -a ~
          ls .roswell
        env:
          PATH: $HOME/.roswell/bin:$PATH
