name: CI
on:
  push:
    branches: [ test-actions ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Download Roswell
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/a8fd8a3c33078d6f06e6cda9d099dcba6fbefcb7/scripts/install-for-ci.sh > install-for-ci.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: install-for-ci.sh
          name: install-script

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: install-script
      - run: |
          head install-for-ci.sh
